name: Build

on:
  push:
    branches: [ 'build', 'kernel-*' ]
  workflow_dispatch:

env:
  BUILD_PATH: ${{ github.workspace }}/build
  OUTPUT_PATH: ${{ github.workspace }}/output
  TARGET_BRANCH: kernel-5.16

jobs:

  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 300 ## TODO: Increase this if necessary! Benchmark a bit, look into caching etc.
    strategy:
      fail-fast: true
    steps:

      - name: Checkout Repository
        timeout-minutes: 15
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}

      - name: Setup Repo
        if: success()
        timeout-minutes: 5
        run: mkdir -p repo packages keys

      - name: Build Packages
        if: success()
        timeout-minutes: 120
        uses: didstopia/cb1-kernel-builder@master
        with:
          repo: github.com/${{ github.repository }}
          branch: ${{ env.TARGET_BRANCH }}
          build-path: ${{ env.BUILD_PATH }}
          output-path: ${{ env.OUTPUT_PATH }}
          target-board: h616
          target-branch: current
          target-build-option: kernel
          target-release: bullseye

      - name: Copy Packages
        if: success()
        timeout-minutes: 5
        run: |
          cp -fr ${{ env.OUTPUT_PATH }}/debs/*.deb ${{ github.workspace }}/packages/

      - name: Build Apt Repository
        if: success()
        timeout-minutes: 5
        uses: didstopia/simple-apt-repo@master
        with:
          # timezone: Europe/Helsinki
          timezone: UTC
          repo-origin: Didstopia CB1 Apt Repo
          repo-label: Didstopia BTT CB1 Apt Repository (2023)
          repo-version: 0.1.0
          repo-description: Didstopia custom apt repository for the BIGTREETECH CB1 hardware, including both stock and custom kernel packages.
          key-email: support@didstopia.com
          key-public: ${{ secrets.APT_REPO_PUBLIC_KEY }}
          key-private: ${{ secrets.APT_REPO_PRIVATE_KEY }}

      - name: Generate Repository File Index
        uses: jayanta525/github-pages-directory-listing@v3.0.0
        with:
          FOLDER: repo

      - name: List Repository Contents
        if: success()
        run: ls -la ${{ github.workspace }}/repo/

      - name: Upload Apt Repository
        if: success()
        timeout-minutes: 15
        uses: actions/upload-pages-artifact@v1
        with:
          # name: github-pages
          path: repo/
          # retention-days: 1

      # - name: Install Dependencies
      #   run: |-
      #     sudo apt-get update && \
      #     sudo apt-get install -y --no-install-recommends \
      #       ccache \
      #       debian-archive-keyring \
      #       debootstrap \
      #       device-tree-compiler \
      #       dwarves \
      #       gcc-11-arm-linux-gnueabihf \
      #       jq \
      #       libbison-dev \
      #       libc6-dev-armhf-cross \
      #       libelf-dev \
      #       libfl-dev \
      #       liblz4-tool \
      #       libpython2.7-dev \
      #       libusb-1.0-0-dev \
      #       pigz \
      #       pixz \
      #       pv \
      #       swig \
      #       pkg-config \
      #       python3-distutils \
      #       qemu-user-static \
      #       u-boot-tools \
      #       distcc \
      #       uuid-dev \
      #       lib32ncurses-dev \
      #       lib32stdc++6 \
      #       apt-cacher-ng \
      #       aptly \
      #       aria2 \
      #       libfdt-dev \
      #       libssl-dev

      # - name: Build Kernel Package
      #   #run: sudo ./build.sh
      #   run: |
      #     export TTY_X=98 && \
      #     export TTY_Y=243 && \
      #     export LINES=98 && \
      #     export COLUMNS=243 && \
      #     export TERM=xterm-256color && \
      #     export BOARD=h616 && \
      #     export BRANCH=current && \
      #     export BUILD_OPT=kernel && \
      #     export RELEASE=bullseye && \
      #     export KERNEL_CONFIGURE=no && \
      #     export MANUAL_KERNEL_CONFIGURE=no && \
      #     export KERNEL_EXPORT_DEFCONFIG=yes && \
      #     sudo ./build.sh \
      #       BOARD=h616 \
      #       BRANCH=current \
      #       BUILD_OPT=kernel \
      #       RELEASE=bullseye \
      #       KERNEL_CONFIGURE=no

      # - name: Publish Kernel Package
      #   uses: Didstopia/apt-repo-action@master
      #   with:
      #     branch: 'apt-repo'
      #     platform: 'arm64'
      #     target: 'bullseye'
      #     # package: 'outputs/debs/linux-image-current-sun50iw9_2.3.2_arm64.deb'
      #     package: 'outputs/debs/*.deb'
      #     version: '2.3.2'
      #     # public_key: ''
      #     # private_key: ''
      #     # private_key_passphrase: ''
      #     dry_run: true
      #     verbose: true

  # Deploy job
  deploy:
    name: Deploy

    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Display Deployment URL
        run: |
          echo "::notice::${{ steps.deployment.outputs.page_url }}"
          echo "URL=${{ steps.deployment.outputs.page_url }}" >> $GITHUB_OUTPUT
