name: Build

on:
  push:
    branches: [ 'build', 'kernel-*' ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'kernel-5.16'
      
      - name: Install Dependencies
        run: |-
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
            ccache \
            debian-archive-keyring \
            debootstrap \
            device-tree-compiler \
            dwarves \
            gcc-arm-linux-gnueabihf \
            jq \
            libbison-dev \
            libc6-dev-armhf-cross \
            libelf-dev \
            libfl-dev \
            liblz4-tool \
            libpython2.7-dev \
            libusb-1.0-0-dev \
            pigz \
            pixz \
            pv \
            swig \
            pkg-config \
            python3-distutils \
            qemu-user-static \
            u-boot-tools \
            distcc \
            uuid-dev \
            lib32ncurses-dev \
            lib32stdc++6 \
            apt-cacher-ng \
            aptly \
            aria2 \
            libfdt-dev \
            libssl-dev

      ## TODO: Implement building the kernel package(s)
      - name: Build Kernel Package
        run: sudo ./build.sh

      - name: Publish Kernel Package
        uses: Didstopia/apt-repo-action@master
        with:
          branch: 'apt-repo'
          platform: 'arm64'
          # target: 'bullseye'
          package: 'foo_1.0.0.deb'
          version: '1.0.0'
          # public_key: ''
          # private_key: ''
          # private_key_passphrase: ''
          dry_run: true
          verbose: true
