name: Build

on:
  push:
    branches: [ 'kernel-*' ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'kernel-5.16'

      - name: Build
        run: touch foo_1.0.0.deb

      - name: Publish
        uses: Didstopia/apt-repo-action@master
        with:
          branch: 'apt-repo'
          platform: 'arm64'
          # target: 'bullseye'
          package: 'foo_1.0.0.deb'
          version: '1.0.0'
          # public_key: ''
          # private_key: ''
          # private_key_passphrase: ''
          dry_run: true
          verbose: true
